from dosaku.modules.samples.song_serializer.json_serializer import JsonSerializer
from dosaku.modules.samples.song_serializer.xml_serializer import XmlSerializer
from dosaku.modules.samples.song_serializer.yaml_serializer import YamlSerializer
from dosaku.modules.samples.chat.echo_bot import EchoBot
from dosaku.modules.samples.chat.red_pajama import RedPajama
from dosaku.modules.go.sabaki import Sabaki
from dosaku.modules.go.random_go_bot import RandomGoBot
from dosaku.modules.stability.clipdrop.text_to_image import ClipdropTextToImage
from dosaku.modules.stability.sd_official import StableDiffusion
from dosaku.modules.ultralytics.yolo8 import Yolo8
from dosaku.modules.meta.sam import SegmentAnything
from dosaku.modules.tencent.gfpgan import GFPGAN1p4
